## Task1
<p>Implement a Python program to generate all sentences where subject is in ["Americans",
"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].</p>

<p><h2>Hint: Subject,Verb and Object should be declared in the program as shown below.</h2></p>
<p>subjects=["Americans ","Indians"]</p>
<p>verbs=["play","watch"]</p>
<p>objects=["Baseball","Cricket"]</p>
<p><h2>Output should come as below:</h2></p>
<p>Americans play Baseball.</p>
<p>Americans play Cricket.</p>
<p>Americans watch Baseball.</p>
<p>Americans watch Cricket.</p>
<p>Indians play Baseball.</p>
<p>Indians play Cricket.</p>
<p>Indians watch Baseball.</p>
<p>Indians watch Cricket.</p>

In [5]:
subject=["Americans", "Indians"] 
verb=["Play", "watch"] 
obj=["Baseball","cricket"] 
# list comprehension... 
sl = [(su+" "+ vb + " " + ob) for su in subject for vb in verb for ob in obj] 
for ss in sl: 
    print (ss)

Americans Play Baseball
Americans Play cricket
Americans watch Baseball
Americans watch cricket
Indians Play Baseball
Indians Play cricket
Indians watch Baseball
Indians watch cricket


## Task2
## Write a function so that the columns of the output matrix are powers of the input vector.
## The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

In [48]:
def vector_mat():
    x=np.array([1,2,3,4,5])
    N=5
    return [x**(N-1-i) for i in range(N)]
dp = vector_mat()
print(np.mat(np.column_stack(dp)))

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]
